[profile.default]
src = 'contracts'
test = 'tests'
out = 'out'
libs = ['lib']
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/"
]

[profile.default.fuzz]
runs = 500

[profile.intense.fuzz]
runs = 5_000